name: Nightly list

on: 
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *"

env:
  FILENAMEANDPATH: config.json
  TEMPDIR: scope
  SECONDREPO: cqa-sandbox/cqa-dashboard-app
  PAT: ${{ secrets.GITHUB_TOKEN }} # Used only for scope tool across GitHub repos
jobs:
  collectdata:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    name: GitHub data scrape repos
    steps:
      - name: Set date in env
        run: |
          echo "MYDATE=$(date +"%FT%H%M")" >> $GITHUB_ENV  
          mkdir -p ${{env.TEMPDIR}}
          # ls -la 
      - name: Before checkout
        run: |
          pwd && ls -la
      - name: Checkout cqa-sandbox/repo-scope-tool
        uses: actions/checkout@master
        with:
          ref: 'main'
          repository: 'cqa-sandbox/repo-scope-tool'
          path: repo-scope-tool
          token: ${{ secrets.DASHBOARD_REPORT_PAT }}
      - name: After repo-scope-tool # output file name ./scope/repos.json
        run: |
          pwd && ls -la
      - name: Checkout cqa-sandbox/cqa-dashboard-app 
        uses: actions/checkout@master
        with:
            ref: 'main'
            repository: 'cqa-sandbox/cqa-dashboard-app'
            token: ${{ secrets.DASHBOARD_REPORT_PAT }}
            path: cqa-dashboard-app 
      - name: After cqa-dashboard-app # output file name ./scope/repos.json
        run: |
          pwd && ls -la            
      - name: Install and Build # output file name ./scope/repos.json
        run: |
          pwd && ls -la
          cd repo-scope-tool
          npm install
          npm run build --if-present
          npm run test --if-present
          npm run start:package:aggregate 
          cd scope && pwd && ls -la
          cp ./repos.json ../cqa-dashboard-app/scope/${{env.MYDATE}}-config.json
      - name: commit file to another repo
        run: |
            pwd && ls -la
            cd ../cqa-dashboard-app
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add .
            git commit -m "generated '${{ env.TEMPDIR }}/${{env.MYDATE}}-${{env.FILENAMEANDPATH}}' "
            git push
            ls -la