name: Nightly list

on: 
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *"

env:
  FILENAMEANDPATH: data.json
  TEMPDIR: nightly
jobs:
  collectdata:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    name: GitHub data scrape repos
    outputs:
      output1: ${{ steps.staticwebdev.outputs.data }}    
      output2: ${{ steps.azure_samples.outputs.data}}
    steps:
      - uses: actions/checkout@master
      - name: Install and Build
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
          npm run start:package:aggregate 
      - name: List files
        id: list_files
        run: |
            cd scope && ls -la 
      - name: Upload artiface
        uses: actions/upload-artifact@v3
        with:
          name: ${{env.MY_DATE}}-scope-github-data.zip # name of artifact to create
          path: ./scope/repos.json # name of existing file/dir to add to artifact             
